# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 076daf0b1a8096f3a433f020abaaf01de5c2ed057b910fd9928803bb86ec907702f4d29d27796dcff085c6de6ec1bcd7ae0d5e39426972c0f641058ae67f741e

test:
  secret_key_base: e1ee74f303619615fbe81d75c171a15f74056e78e03db7e9c12663b2bf5cdbf8445bebc49b208af83f47d251288ba6c72fd2e7abf5fafdc891e770bc5ce8870e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
